[2024-11-14T02:28:44.584+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-14T02:28:44.614+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AlphaVantageTimeSeriesDaily_AAPL_MSFT.load manual__2024-11-14T02:28:38.169157+00:00 [queued]>
[2024-11-14T02:28:44.621+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AlphaVantageTimeSeriesDaily_AAPL_MSFT.load manual__2024-11-14T02:28:38.169157+00:00 [queued]>
[2024-11-14T02:28:44.622+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-14T02:28:44.634+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2024-11-14 02:28:38.169157+00:00
[2024-11-14T02:28:44.642+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'AlphaVantageTimeSeriesDaily_AAPL_MSFT', 'load', 'manual__2024-11-14T02:28:38.169157+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/ETLstockprice.py', '--cfg-path', '/tmp/tmpb2wooju5']
[2024-11-14T02:28:44.644+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=756) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-14T02:28:44.645+0000] {standard_task_runner.py:91} INFO - Job 142: Subtask load
[2024-11-14T02:28:44.645+0000] {standard_task_runner.py:63} INFO - Started process 769 to run task
[2024-11-14T02:28:44.690+0000] {task_command.py:426} INFO - Running <TaskInstance: AlphaVantageTimeSeriesDaily_AAPL_MSFT.load manual__2024-11-14T02:28:38.169157+00:00 [running]> on host b955513b8419
[2024-11-14T02:28:44.778+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AlphaVantageTimeSeriesDaily_AAPL_MSFT' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T02:28:38.169157+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T02:28:38.169157+00:00'
[2024-11-14T02:28:44.780+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-14T02:28:44.788+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-11-14T02:28:44.790+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-11-14T02:28:44.791+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-11-14T02:28:45.499+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-14T02:28:45.499+0000] {ETLstockprice.py:102} ERROR - Error loading data into Snowflake: 002003 (42S02): 01b85b34-0004-2cf3-0000-00027a6fc271: SQL compilation error:
Object 'DEV.RAW_DATA.STOCK_DATA' does not exist or not authorized.
[2024-11-14T02:28:45.500+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-14T02:28:45.500+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ETLstockprice.py", line 103, in load
    raise e
  File "/opt/airflow/dags/ETLstockprice.py", line 77, in load
    cursor.execute(f"""
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (42S02): 01b85b34-0004-2cf3-0000-00027a6fc271: SQL compilation error:
Object 'DEV.RAW_DATA.STOCK_DATA' does not exist or not authorized.
[2024-11-14T02:28:45.510+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=AlphaVantageTimeSeriesDaily_AAPL_MSFT, task_id=load, run_id=manual__2024-11-14T02:28:38.169157+00:00, execution_date=20241114T022838, start_date=20241114T022844, end_date=20241114T022845
[2024-11-14T02:28:45.524+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 142 for task load (002003 (42S02): 01b85b34-0004-2cf3-0000-00027a6fc271: SQL compilation error:
Object 'DEV.RAW_DATA.STOCK_DATA' does not exist or not authorized.; 769)
[2024-11-14T02:28:45.542+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-14T02:28:45.557+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-14T02:28:45.561+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
