[2024-11-14T05:41:31.183+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-14T05:41:31.271+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-14T05:41:30.125754+00:00 [queued]>
[2024-11-14T05:41:31.293+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-14T05:41:30.125754+00:00 [queued]>
[2024-11-14T05:41:31.295+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-14T05:41:31.331+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-14 05:41:30.125754+00:00
[2024-11-14T05:41:31.344+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run', 'manual__2024-11-14T05:41:30.125754+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp00b_f9eh']
[2024-11-14T05:41:31.354+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3647) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-14T05:41:31.355+0000] {standard_task_runner.py:91} INFO - Job 169: Subtask dbt_run
[2024-11-14T05:41:31.356+0000] {standard_task_runner.py:63} INFO - Started process 3648 to run task
[2024-11-14T05:41:31.475+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-14T05:41:30.125754+00:00 [running]> on host 5c9ef59c8996
[2024-11-14T05:41:31.703+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T05:41:30.125754+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T05:41:30.125754+00:00'
[2024-11-14T05:41:31.704+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-14T05:41:31.721+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-14T05:41:31.724+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-14T05:41:31.728+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-14T05:41:31.731+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 234, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 77, in run_command
    self.sub_process = Popen(
                       ^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1872, in _execute_child
    env_list.append(k + b'=' + os.fsencode(v))
                               ^^^^^^^^^^^^^^
  File "<frozen os>", line 818, in fsencode
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2024-11-14T05:41:31.783+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run, run_id=manual__2024-11-14T05:41:30.125754+00:00, execution_date=20241114T054130, start_date=20241114T054131, end_date=20241114T054131
[2024-11-14T05:41:31.810+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 169 for task dbt_run (expected str, bytes or os.PathLike object, not NoneType; 3648)
[2024-11-14T05:41:31.824+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-14T05:41:31.846+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-14T05:41:31.854+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
